<script src="public/js/public.js"></script>
<div class="container">
    <div class="row">
        <div class="col-xs-12">
            <!-- Nav tabs -->
            <ul class="nav nav-tabs" role="tablist">
               <?php require('controllers/content_private_list.php');?>
            </ul>
        </div><!-- Tab panes -->
        <div class="col-xs-12">
            <div class="chatbox">

            </div>
        </div>
        <div class="col-xs-12">
            <form action="" methode="POST" class="form_chat_private">
                <div class="input-group">
                    <input type="text" class="form-control message_chat" name="message_chat" placeholder="Message">
			      	<span class="input-group-btn">
			        	<button class="btn btn-default" type="submit">
                            <span style='line-height : inherit' class="glyphicon glyphicon-send"
                                  aria-hidden="true"></span>
                        </button>
			      	</span>
                </div>
            </form>
        </div>
    </div>
</div>

<script>
    $('#myTabs a').click(function (e) {
        e.preventDefault()
        $(this).tab('show')
    })
</script>