<script type="text/javascript">
	$(document).ready(function() {
		function getMessage()
		{
			$.post("index.php?page=chat", {handler: "public", action: "recept"},function(data)
			{
				console.log(data);
				$('.chatbox').html(data);
			})
		}
		getMessage();
		// setInterval(getMessage, 1000);

		$('.form_chat').submit( function (){
			var id_user = <?php echo $_SESSION['id'];?>;
			var content = $('.message_chat').val();
			var action = $('.message_action').val();
			$.post('index.php?page=chat', { handler: "public", message_id_sender: id_user, message_content: content ,action: action}, function(status){
				$('.chatbox').append(status);
				$('.message_chat').val(''); 
			});
			getMessage();

			return false;
		}) 
	})


</script>

<div class="container">
	<div class="row">
		<div class="col-xs-12">
			<div class="chatbox">
				
			</div>
		</div>
		<div class="col-xs-12">
			<form action="" methode="POST" class="form_chat">
				<input type="hidden" name="message_action" class="message_action" value="send" >
				<div class="form-group">
					<div class="col-xs-11">
						<input type="text" placeholder="Message" name="message_chat" class="message_chat">
					</div>
					<div class="col-xs-1">
						<button type="submit"><span class="glyphicon glyphicon-send" aria-hidden="true"></span></button>
					</div>
				</div>

			</form>
		</div>
	</div>
</div>