<div class="container">
	<div class="row">
		<div class="col-xs-12">
			<div class="chatbox">
				
			</div>
		</div>
		<div class="col-xs-12">
			<form action="" methode="POST">
				<input type="hidden" value="send">
				<div class="form-group">
					<div class="col-xs-11">
						<input type="text" placeholder="Message">
					</div>
					<div class="col-xs-1">
						<button type="submit"><span class="glyphicon glyphicon-send" aria-hidden="true"></span></button>
					</div>
				</div>

			</form>
		</div>
	</div>
</div>