<form action="" methode="POST">
  <div class="form-group col-xs-12 col-sm-6">
	<label for="name">Name</label>
	<input type="text" name="register_name" class="form-control" id="register_name" placeholder="Password">
  </div>
  <div class="form-group col-xs-12 col-sm-6">
	<label for="email">Email address</label>
	<input type="email" name="register_email" class="form-control" id="email" placeholder="Email">
  </div>
  <div class="form-group col-xs-12 col-sm-6">
	<label for="password">Password</label>
	<input type="password" name="register_password" class="form-control" id="password" placeholder="8 - 20">
  </div>
  <div class="form-group col-xs-12 col-sm-6">
	<label for="password-repeat">Password repeat</label>
	<input type="password" name="register_password_repeat" class="form-control" id="password-repeat" placeholder="8 - 20">
  </div>
  <button type="submit" class="btn btn-default">Submit</button>
</form>