<div class="container">
	<div class="row">
	<form action="" method="post">
		<input type="hidden" name="action" value="login" />
		<div class="row">
			<div class="form-group col-xs-6">
				<label for="login_email">Adresse email</label>
				<input type="email" class="form-control" name="login_email" id="login_email" placeholder="Email adress" value="<?php if(isset($email)){echo htmlentities($email);}?>">
			</div>
			<div class="form-group col-xs-6">
				<label for="login_password">Mot de passe</label>
				<input type="password" class="form-control" name="login_password" id="login_password" placeholder="Password">
			</div>
		</div>
		<button type="submit" class="btn btn-default">Log-in</button>
	</form>
	</div>
</div>