<div class="container">
	<div class="row">
	<h2>S'enregister</h2>
	<form  action="?page=login" method="post">
		<input type="hidden" name="action" value="login" />
		<div class="row">
			<div class="form-group col-xs-6">
				<label for="exampleInputEmail1">Adresse email</label>
				<input type="email" class="form-control" name="login_email" id="login_email" placeholder="Adresse email" value="<?php if(isset($email)){echo htmlentities($email);}?>">
			</div>
			<div class="form-group col-xs-6">
				<label for="exampleInputPassword1">Mot de passe</label>
				<input type="password" class="form-control" name="login_password" id="login_password" placeholder="Mot de passe">
			</div>
		</div>
		<button type="submit" class="btn btn-default">Envoyer</button>
	</form>
	</div>
</div>