<script src="public/js/public.js"></script>

<div class="container">
	<div class="row">
		<div class="col-xs-12 col-sm-9">
			<h3>Chat</h3>
			<div class="chatbox">
				
			</div>
		</div>
		<div class="hidden-xs col-sm-3">
			<div class="users-online text-right">
				<h3>Users</h3>
				<ul class="user-list list-unstyled">
					
				</ul>
			</div>
		</div>
		<div class="col-xs-12 col-sm-9">
			<form action="" methode="POST" class="form_chat">
				<div class="input-group">
					<input type="text" class="form-control message_chat" name="message_chat" placeholder="Message">
			      	<span class="input-group-btn">
			        	<button class="btn btn-default" type="submit"><span style='line-height : inherit' class="glyphicon glyphicon-send" aria-hidden="true"></span></button>
			      	</span>
			    </div>
			</form>
		</div>
	</div>
</div>