<div class="navbar navbar-inverse navbar-fixed-top">
	<a class="navbar-brand" href="index.php">Le Chat</a>
	<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
	<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	  	<ul class="nav navbar-nav">
	  	<?php if (!isset($_SESSION['id'])) { ?>
			<li <?php if($page=='login'){echo 'class="active"';};?>><a href="?page=login">Login</a></li>
			<li <?php if($page=='register'){echo 'class="active"';};?>><a href="?page=register">Register</a></li>
	  	<?php } else {?>
		  		<li <?php if($page=='register'){echo 'class="active"';};?>><a href="?page=logout">Logout</a></li>
				<li <?php if($page=='register'){echo 'class="active"';};?>><a href="?page=chat">Chat</a></li>
				<li <?php if($page=='register'){echo 'class="active"';};?>><a href="?page=private">Private</a></li>
		<?php if ($currentUser->getStatus() == STATUS_ADMIN ) { ?>
					<li <?php if($page=='register'){echo 'class="active"';};?>><a href="?page=dashboard">Dashboard</a></li>
		<?php }}?>	
	   	</ul>
	</div>
</div>
